n=int(input())
N=list(map(int,input().split()))
m=int(input())
M=list(map(int,input().split()))
#print(n,"-->",N)
#print(m,"-->",M)
N=set(N)
M=set(M)
s=N.symmetric_difference(M)
#print(s)
M=sorted(M)
N=sorted(N)
#print(N," ",M)
l=list(s)
#print(l)
for i in l:
    print(i)
