qty=int(input("Enter the quantity : "))
val=float(input("Enter the cost : "))
disc=int(input("Enter the discount % : "))
tax=int(input("Enter the tax % : "))
amt=qty*val
amt=amt-((amt*disc)/100)
amt=amt+((amt*tax)/100)
print("------------BILL-----------")
print("Qty : ",qty)
print("Cost : ",val)
print("Discount : ",disc)
print("Tax : ",tax)
print("Total cost : ",amt)
print("---------------------------")