from tkinter import *
window=Tk()
window.title('Welcome')
window.minsize(width=200,height=400)
window.maxsize(width=700,height=800)
#label
l1=Label(window,text='emp name',bg='blue',fg='white')
l1.place(x=0,y=10)
def edtech():
    x=v.get()
    print(x)
    l2.config(text=x,bg='yellow',fg='black')
v=StringVar()
e1=Entry(window,font=('corbel',18),bd=5,textvariable=v)
e1.place(x=80,y=10)
b1=Button(window,text='Enter',fg='yellow',bg='green',command=edtech)
b1.place(x=120,y=60)
l2=Label(window,text='nothing',bg='brown',fg='black')
l2.place(x=120,y=100)
window.mainloop()